on: push

name: Integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build -o myproject2

